version: '3.9'
services:
  #db-service
  postgresdb:
    image: postgres:15.1-alpine
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    ports:
      - 5432:5432
    hostname: db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - web-net
  #backend-web-service
  app:
    container_name: goweb_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    tty: true
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - web-net

volumes:
  pg_data:
  sqlclocal:
    name: sqlclocal
    driver: local
    driver_opts:
      type: none
      device: /home/crzywrld/goprojects/web/db/sqlclocal
      o: bind

networks:
  web-net:
    driver: bridge